### PR TITLE
Return `Arc` instead of `Rc` from the iterators to make them `Send`

### PR DESCRIPTION
**Pull request by koute**
This PR replaces the `Rc` that's returned by the iterators with an `Arc`.

I need this to make the iterators `Send`, which I need for further performance improvements in `substrate`.

### CODE REVIEW

**Review by altonen — APPROVED** [review]

**Comment by cheme** [comment]
Does TrieDBNodeIterator need to be Send (if not, could also make send the other needed iterators as long as they cannot leek rc (the internal triedbnodeiterator))?

**Review by bkchr — APPROVED** [review]
A good old `is_sync` test maybe?

**Review by melekes — APPROVED** [review]
👍

**Comment by koute** [comment]
> Does TrieDBNodeIterator need to be Send (if not, could also make send the other needed iterators as long as they cannot leek rc (the internal triedbnodeiterator))?

I just need `TrieDBRawIterator` to be `Send`, but since `TrieDBNodeIterator` is a thin wrapper around it it'll also automatically become `Send`. There are no other `Rc`s anywhere left so I think everything now will be `Send` anyway?

> A good old `is_sync` test maybe?

Good idea. I'll add it.

**Pull request merged**
